databases:
  - name: rails-react-biketour
    databaseName: rails-react-biketour
    user: rails-react-biketour

services:
  - type: web
    name: rails-react-biketour
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-react-biketour
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false